server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/amerbank?currentSchema=account
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    schemas: account
    enabled: true
    locations: classpath:db/migration/account

jwt:
  secret: ${JWT_SECRET}
  serviceTokenExpirationMs: 120000
  expirationMs: 3600000

account:
  prefix: "ACCT"
  body-digits: 10
  upper-bound: 10000000000
  max-attempts: 5
  initial-balance: 1000.00

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health
