server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/amerbank?currentSchema=audit_log
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    schemas: audit_log
    enabled: true
    locations: classpath:db/migration/audit
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: audit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.amerbank.audit_logging.dto.AuditEventMessage
        spring.json.trusted.packages: com.amerbank.*

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health
