server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/amerbank?currentSchema=auth
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:postgresql://postgres:5432/amerbank
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: auth
    enabled: true
    locations: classpath:db/migration/auth
eureka:
  instance:
    hostname: auth-server
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 3600000
  serviceTokenExpirationMs: 120000

management:
  endpoints:
    web:
      exposure:
        include: health
