spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amerbank?currentSchema=customer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    outOfOrder: true
    schemas: customer
    enabled: true
    locations: classpath:db/migration/customer
auth:
  service:
    url: http://auth-server
    timeout: 5000
    register:
      path: /auth/internal/register
    user-by-email:
      path: /admin/auth/users/by-email
kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: customer-service
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
customer:
  trace-id-header: TRACE_ID_HEADER
  request-id-header: REQUEST_ID_HEADER
  auth-service-url: http://auth-server
  auth-register-path: /auth/internal/register
  auth-user-by-email-path: /admin/auth/users/by-email


jwt:
  secret: ${JWT_SECRET}
