apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: amerbank/account:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: amerbank-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amerbank-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: amerbank-secrets
                  key: JWT_SECRET
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "account"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "false"
          envFrom:
            - configMapRef:
                name: account-config
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
